### ISSUE TITLE
How can i use it on vuejs on vuestic-admin?

### ISSUE THREAD

**Issue by youyi1314** [orhanveli/medium-editor-embed-button#4]
how can i add this on : [Vuestic-Admin](https://github.com/epicmaxco/vuestic-admin/blob/master/src/vuestic-theme/vuestic-components/vuestic-medium-editor/VuesticMediumEditor.vue)

I tried put below at line 9:
require('medium-editor-embed-button')
or
require('medium-editor-embed-button/dist/js/medium-editor-embed-button.js')
or 
const meEnbedButton = require('medium-editor-embed-button/dist/js/medium-editor-embed-button.js')

and put 
`extensions: {
            embedButton: new EmbedButtonExtension()
        },`
after line 18
and also added **_embedButton_** to the buttons after line 28
but it show 

> Uncaught ReferenceError: MediumEditor is not defined
    at eval (medium-editor-embed-button.js?77be:681)

how can i fixed this?
Thanks

**Comment by orhanveli** [comment]
Hello @youyi1314
I haven't develop on this project for a long time. I think you didn't include MediumEditor to your page.

You should reference mediumeditor JS file to page (before your JS files)
If you are using webpack or any other package resolver, you should define MediumEditor as external library.

there should be no problem in this case.

**Comment by orhanveli** [comment]
and some folk resolve this issue :)

https://github.com/sainuio/medium-editor-embed-button/commit/a9ca4070f05c3b916288784774fe77949f13f9d0

**Comment by youyi1314** [comment]
@orhanveli Thanks, it work after i adding 
https://github.com/sainuio/medium-editor-embed-button/commit/a9ca4070f05c3b916288784774fe77949f13f9d0

Use it like:
`  import EmbedButton from 'medium-editor-embed-button/dist/js/medium-editor-embed-button'`
and 
`          extensions: {embedButton: new EmbedButton()},`
